In [2]:
#!/usr/bin/env python

# make sure to install these packages before running:
# pip install pandas
# pip install sodapy

import pandas as pd
from sodapy import Socrata

# Unauthenticated client only works with public data sets. Note 'None'
# in place of application token, and no username or password:
client = Socrata("data.cityofchicago.org", None)

# Example authenticated client (needed for non-public datasets):
# client = Socrata(data.cityofchicago.org,
#                  MyAppToken,
#                  userame="user@example.com",
#                  password="AFakePassword")

# First 2000 results, returned as JSON from API / converted to Python list of
# dictionaries by sodapy.
results = client.get("v6vf-nfxy", limit=5000)

# Convert to pandas DataFrame
results_df = pd.DataFrame.from_records(results)

Collecting sodapy
  Downloading sodapy-2.1.0-py2.py3-none-any.whl (14 kB)
Requirement already satisfied: requests>=2.20.0 in c:\users\mdurr\anaconda3\lib\site-packages (from sodapy) (2.22.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\mdurr\anaconda3\lib\site-packages (from requests>=2.20.0->sodapy) (1.25.8)
Requirement already satisfied: idna<2.9,>=2.5 in c:\users\mdurr\anaconda3\lib\site-packages (from requests>=2.20.0->sodapy) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\mdurr\anaconda3\lib\site-packages (from requests>=2.20.0->sodapy) (2019.11.28)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\mdurr\anaconda3\lib\site-packages (from requests>=2.20.0->sodapy) (3.0.4)
Installing collected packages: sodapy
Successfully installed sodapy-2.1.0

WARNING:root:Requests made without an app_token will be subject to strict throttling limits.

In [3]:
results_df.head()

,sr_number,sr_type,sr_short_code,owner_department,status,created_date,last_modified_date,street_address,zip_code,street_number,...,location,:@computed_region_rpca_8um6,:@computed_region_vrxf_vc4k,:@computed_region_6mkv_f3dw,:@computed_region_bdys_3d7i,:@computed_region_43wa_7qmu,closed_date,city,state,parent_sr_number
0,SR20-05000063,Liquor Establishment Complaint,LIQUORCO,BACP - Business Affairs and Consumer Protection,Open,2020-09-05T18:14:49.000,2020-09-05T18:14:51.000,2933 W MONTROSE AVE,60618,2933,...,"{'latitude': '41.96106086375513', 'longitude':...",39,16,21538,214,20,NaN,NaN,NaN,NaN
1,SR20-05000062,Street Light Out Complaint,SFD,CDOT - Department of Transportation,Open,2020-09-05T18:14:33.000,2020-09-05T18:14:46.000,10629 S EGGLESTON AVE,60628,10629,...,"{'latitude': '41.700686204883404', 'longitude'...",19,45,21861,525,22,NaN,NaN,NaN,NaN
2,SR20-05000061,Yard Waste Pick-Up Request,SCQ,Streets and Sanitation,Open,2020-09-05T18:14:30.000,2020-09-05T18:14:30.000,2646 N DRAKE AVE,60647,2646,...,"{'latitude': '41.92962887141283', 'longitude':...",1,23,22535,72,12,NaN,NaN,NaN,NaN
3,SR20-05000060,Rodent Baiting/Rat Complaint,SGA,Streets and Sanitation,Open,2020-09-05T18:14:27.000,2020-09-05T18:14:41.000,11531 S NORMAL AVE,60628,11531,...,"{'latitude': '41.68428708282108', 'longitude':...",19,50,21861,255,22,NaN,NaN,NaN,NaN
4,SR20-05000059,Street Light Pole Damage Complaint,SFK,CDOT - Department of Transportation,Open,2020-09-05T18:14:08.000,2020-09-05T18:14:21.000,6410 W BELMONT AVE,60634,6410,...,"{'latitude': '41.93834612147599', 'longitude':...",52,17,22254,396,44,NaN,NaN,NaN,NaN

In [5]:
results_df.shape

(5000, 39)

In [6]:
results_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 39 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   sr_number                    5000 non-null   object
 1   sr_type                      5000 non-null   object
 2   sr_short_code                5000 non-null   object
 3   owner_department             5000 non-null   object
 4   status                       5000 non-null   object
 5   created_date                 5000 non-null   object
 6   last_modified_date           5000 non-null   object
 7   street_address               4996 non-null   object
 8   zip_code                     4994 non-null   object
 9   street_number                4996 non-null   object
 10  street_direction             4996 non-null   object
 11  street_name                  4996 non-null   object
 12  street_type                  4980 non-null   object
 13  duplicate                    5000 non-null   bool
 14  legacy_record                5000 non-null   bool
 15  community_area               4903 non-null   object
 16  ward                         4905 non-null   object
 17  electricity_grid             4158 non-null   object
 18  police_sector                4905 non-null   object
 19  police_district              4905 non-null   object
 20  police_beat                  4905 non-null   object
 21  precinct                     4900 non-null   object
 22  created_hour                 5000 non-null   object
 23  created_day_of_week          5000 non-null   object
 24  created_month                5000 non-null   object
 25  x_coordinate                 4911 non-null   object
 26  y_coordinate                 4911 non-null   object
 27  latitude                     4911 non-null   object
 28  longitude                    4911 non-null   object
 29  location                     4911 non-null   object
 30  :@computed_region_rpca_8um6  4901 non-null   object
 31  :@computed_region_vrxf_vc4k  4901 non-null   object
 32  :@computed_region_6mkv_f3dw  4911 non-null   object
 33  :@computed_region_bdys_3d7i  4903 non-null   object
 34  :@computed_region_43wa_7qmu  4901 non-null   object
 35  closed_date                  3372 non-null   object
 36  city                         3104 non-null   object
 37  state                        3104 non-null   object
 38  parent_sr_number             263 non-null    object
dtypes: bool(2), object(37)
memory usage: 1.4+ MB

In [8]:
results_df.status.value_counts()

Completed    3350
Open         1628
Canceled       22
Name: status, dtype: int64